// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.browser.urlbar.matchBuckets", "suggestion:4,general:5");
user_pref("app.normandy.user_id", "3928dc2d-7eae-4429-8464-e15f687b0abd");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 1526988932);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1526644572);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1526648014);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1526644541);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 66);
user_pref("browser.newtabpage.activity-stream.impressionId", "{5fb926e5-29ef-44e6-a107-8f35026d3a80}");
user_pref("browser.newtabpage.activity-stream.migrationExpired", true);
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1526576400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1526647988);
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1526988905082");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1526992505082");
user_pref("browser.search.countryCode", "RU");
user_pref("browser.search.region", "RU");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180516032328");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1526988902");
user_pref("browser.slowStartup.averageTime", 1571);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180516032328");
user_pref("browser.startup.homepage_override.mstone", "60.0.1");
user_pref("browser.startup.page", 0);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\",\"webide-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Яндекс");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1526644545736");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("devtools.telemetry.tools.opened.version", "{\"DEVTOOLS_SCREEN_RESOLUTION_ENUMERATED_PER_USER\":\"60.0.1\"}");
user_pref("devtools.toolbox.selectedTool", "netmonitor");
user_pref("distribution.iniFile.exists.appversion", "60.0.1");
user_pref("distribution.iniFile.exists.value", false);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 24);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180516032328");
user_pref("extensions.lastAppVersion", "60.0.1");
user_pref("extensions.lastPlatformVersion", "60.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"dm@westbyte.com\":\"32c4425b-ba72-40ca-9224-75567897d179\",\"screenshots@mozilla.org\":\"43663e14-1dbd-4d6d-afd9-e5ef4492c5b7\"}");
user_pref("gecko.handlerService.migrated", true);
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("media.benchmark.vp9.fps", 111);
user_pref("media.benchmark.vp9.versioncheck", 3);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x1916");
user_pref("sanity-test.driver-version", "22.20.16.4836");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20180516032328");
user_pref("security.disable_button.openCertManager", false);
user_pref("security.sandbox.content.tempDirSuffix", "{e68c8829-db0e-477c-a422-775e9dc75be0}");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.clients.lastSyncLocal", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("services.sync.tabs.lastSyncLocal", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1526988901);
user_pref("toolkit.telemetry.cachedClientID", "9cd94fbd-a0f8-4f76-953b-49ce382ce17e");
user_pref("toolkit.telemetry.previousBuildID", "20180516032328");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
